name: inventarios
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  go_router: ^7.1.1
  sqflite: ^2.2.8+4
  path: ^1.8.3
  uuid: ^3.0.7
  image_picker: ^0.8.7+5
  path_provider: ^2.0.15
  intl: ^0.17.0
  pdf: ^3.6.0
  printing: ^5.9.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  

